name: CI
on: [push, pull_request]

jobs:
  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - run: pip install setuptools vim-vint
      - run: vint --warning --verbose --enable-neovim ./autoload ./plugin
